### ISSUE TITLE
Least Authority rust std/core libs

### ISSUE THREAD

**Issue by dckc** [dckc/rust#2]
goal: libraries get no ambient authority; all authority comes from main programs

audit for ambient authority (random, time, ...)
task local storage is global mutable state? or is it folly to try to isolate less than a task?

**Comment by dckc** [comment]
mkdtemp()
oh... and use file descriptors rather than paths

**Comment by dckc** [comment]
rust rt/args has a FIXME for args (which are ambient authority)
https://github.com/rust-lang/rust/issues/7756 Better way to store command line arguments?

TODO: find the haskell compiler history around global args and how it prevents parallel compilation or some such.
found the discussion from 2012-08-09 #haskell http://ircbrowse.net/browse/haskell?id=13957476&timestamp=1344474950#t1344474950

2012-08-09 03:20:30 +0200   <danil>     DanC: http://www.aosabook.org/en/ghc.html , look for "crime doesn't pay"

**Comment by dckc** [comment]
> I know that defining purity precisely can be challenging in multi-paradigm language but there is a very useful most basic notion "function that does not access any global state other than via arguments".
> -- [More casual hacking: Thoughts about Rust from D programmer](https://blog.dicebot.lv/posts/2015/01/thoughts_about_rust_from_d_programmer)
> bookmarked Jan 14, 2015
> https://diigo.com/07w9dk

**Comment by dckc** [comment]
see also https://github.com/rust-lang/rust/issues/3094#issuecomment-9589749 Non-determinism as an effect.

**Comment by briansmith** [comment]
Doesn't the entire design of futures.rs require ambient authority? My understanding is that all the scheduling is handled through a hidden back channel of mutable global state.

**Comment by dckc** [comment]
Yes, it does look that way:

``` rust
thread_local!(static CURRENT_TASK: Cell<(*const Task, *const data::LocalMap)> = {
    Cell::new((0 as *const _, 0 as *const _))
});
```

 -- [task/mod.rs](https://docs.rs/futures/0.1/src/futures/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.3/src/task/mod.rs.html#134-136)

This comes back part of my original Oct 2012 comment:

> task local storage is global mutable state? or is it folly to try to isolate less than a task?

("task" back then is closer to "thread" now.)

I'm still thinking this through...

**Comment by briansmith** [comment]
It seems like this should be combined with a lint addition prohibiting `static mut`.

**Comment by briansmith** [comment]
https://github.com/NuxiNL/cloudlibc has some interesting ideas, such as passing the application a file descriptor to the directory/directories it is allowed to access, instead of letting it open files by path. Presumably paths have to be constructed relative to those root file descriptors.

**Comment by dckc** [comment]
Right... That's what I meant in https://github.com/dckc/rust/issues/2#issuecomment-9764612:

> oh... and use file descriptors rather than paths

**Comment by dckc** [comment]
[tag_safe](https://github.com/thepowersgang/tag_safe/) looks handy!
example: [larust-tame](https://github.com/dckc/larust-tame) a68fa1a0c7c5b62ab4b70124e91d519f90eb6e16

[issue 1](https://github.com/thepowersgang/tag_safe/issues/1): can we use it to tag std functions?

**Comment by ratmice** [comment]
lacking an heap allocations is there actually any ambient authority in the core library?
A potential alternative to tag_safe seems to be mentioned here:
https://github.com/rust-lang/rust/issues/27783#issuecomment-251444891

then building up a variation of std which just drops the file/time/randomness leaving the portions of std wanted intact
[edit] I see now that this issue predates the existence of the "libcore" library, to which i was referring to
https://doc.rust-lang.org/core/

**Comment by dckc** [comment]
right... a variation of std is what I'm hoping for:

> there is renewed interst in refactoring std for ultimate portability. One result of this could be a std alternative with no ambient authority. -- [my wishlist](http://www.madmode.com/2017/ocap-wish-list.html)

**Comment by dckc** [comment]
More motivation:

> I can share my technique for patching 'std' though in vague terms. First of all, it's pretty hacky, my goal was not to port 'std' in its entirety, just enough to get things to run. It turns out, there's not THAT much to do anyway, because there are huge swaths of things that just are impossible to port to consoles anyway, like **anything to do with the network or spawning processes etc.**
-- https://www.reddit.com/r/rust/comments/78bowa/hey_this_is_kyren_from_chucklefish_we_make_and/dosn15b/

**Comment by dckc** [comment]
and more:

> The standard library has many stubbed out components which (as far as I know) immediately return errors when used. For example using threads will immediately return errors (likely then causing a panic) and I believe similar functionality like TCP/UDP will also tend to return an error pretty quickly.
 -- https://internals.rust-lang.org/t/state-of-webassembly-and-rust/60

**Comment by briansmith** [comment]
It would be great to somehow combine this effort with the steed effort, and/or perhaps redo steed as an incremental rewrite of the linux-musl-libc target and/or the cloud to a pure Rust libstd that removes all the stuff that is problematic with respect to this (perhaps using CloudABI as inspiration). LMK if you'd be interested in pursing any such efforts.

See also https://lwn.net/Articles/433326/, which people mentioned recently as motivation for a capability-based stdlib.

See also https://github.com/benlaurie/go-capsicum.

**Comment by dckc** [comment]
Steed? oh... https://github.com/japaric/steed . nifty. Thanks.

**Comment by dckc** [comment]
Note discussion of [malicious crates][1].

[1]: https://internals.rust-lang.org/t/an-idea-to-mitigate-attacks-through-malicious-crates/9006/52?u=dckc

**Comment by dckc** [comment]
ooh! https://github.com/sunfishcode/cap-std

**Comment by dckc** [comment]
Yay! they did it!

https://crates.io/crates/cap-std is an ocap work-alike for std

https://github.com/sunfishcode/ambient-authority/blob/main/clippy.toml is a taming database for std.

ref https://github.com/bytecodealliance/cap-std/issues/130#issuecomment-861018968
